import math

def input_constraints(v_launch, theta, p_target):
    outfile = open("log.txt", "a")
    print("function input_constraints called with inputs: {", file=outfile)
    print("  v_launch = ", end='', file=outfile)
    print(v_launch, end='', file=outfile)
    print(", ", file=outfile)
    print("  theta = ", end='', file=outfile)
    print(theta, end='', file=outfile)
    print(", ", file=outfile)
    print("  p_target = ", end='', file=outfile)
    print(p_target, file=outfile)
    print("  }", file=outfile)
    outfile.close()
    
    if (not(v_launch > 0)) :
        print("Warning: ", end='')
        print("v_launch has value ", end='')
        print(v_launch, end='')
        print(" but suggested to be ", end='')
        print("above ", end='')
        print(0, end='')
        print(".")
    if (not(0 < theta and theta < math.pi / 2)) :
        print("Warning: ", end='')
        print("theta has value ", end='')
        print(theta, end='')
        print(" but suggested to be ", end='')
        print("between ", end='')
        print(0, end='')
        print(" and ", end='')
        print(math.pi / 2, end='')
        print(" ((pi)/(2))", end='')
        print(".")
    if (not(p_target > 0)) :
        print("Warning: ", end='')
        print("p_target has value ", end='')
        print(p_target, end='')
        print(" but suggested to be ", end='')
        print("above ", end='')
        print(0, end='')
        print(".")
