def get_input(filename):
    outfile = open("log.txt", "a")
    print("function get_input called with inputs: {", file=outfile)
    print("  filename = ", end='', file=outfile)
    print(filename, file=outfile)
    print("  }", file=outfile)
    outfile.close()
    
    infile = open(filename, "r")
    infile.readline()
    v_launch = float(infile.readline())
    outfile = open("log.txt", "a")
    print("var 'v_launch' assigned to ", end='', file=outfile)
    print(v_launch, end='', file=outfile)
    print(" in module InputFormat", file=outfile)
    outfile.close()
    infile.readline()
    theta = float(infile.readline())
    outfile = open("log.txt", "a")
    print("var 'theta' assigned to ", end='', file=outfile)
    print(theta, end='', file=outfile)
    print(" in module InputFormat", file=outfile)
    outfile.close()
    infile.readline()
    p_target = float(infile.readline())
    outfile = open("log.txt", "a")
    print("var 'p_target' assigned to ", end='', file=outfile)
    print(p_target, end='', file=outfile)
    print(" in module InputFormat", file=outfile)
    outfile.close()
    infile.close()
    
    return v_launch, theta, p_target
